model_path: "ggomarobot/KSSDS"
tokenizer_path: "ggomarobot/KSSDS"

# input_tsv 와 input_sequence 중 한가지 옵션 택일 (tsv 파일 혹은 text string)
input_tsv: "./tests/general_test.tsv"  # Input TSV file path (leave blank if using text)
input_sequence: "" # Input text for sentence splitting (leave blank if using input_tsv)

output_tsv: "./KSSDS_HF_HUB_test.tsv"  # Output TSV file path
output_print: true # Whether split sentence outputs will be printed out on terminal

max_length: 512

# KSSDS 를 사용할 tsv 파일의 Row 이름들
input_columns:
  file_path: "File Path"  # Column name for transcription file paths
  transcription: "Transcription"  # Column name for transcriptions

# STT 모델의 할루시네이션으로 한 글자가 계속 반복될 시 그 반복된 단어를 문장처럼 분리해내기 위한 parameter 들
repetition_detection:
  max_repeats: 60 # 한 문장으로 인정할 최대 반복 수
                  # max_repeats: 60 일 시, 같은 단어가 75자 반복되면 60자 / 15자 두 문장으로 분리됨
  detection_threshold: 70 # 반복 감지를 위한 최소 단어 수
                          # detection_threshold: 70 일 시, 70개 단어 이하 텍스트는 반복이 있더라도 감지하지 않음
  max_phrase_length: 2 # 최대 반복 구절 길이
                       # max_phrase_length: 2 일 시,
                       # 한 단어 반복 "아 아 아 아 아 아 ..."
                       # 두 단어 반복 "음 그러면 음 그러면 음 그러면 음 그러면 ..."
                       # 까지만 감지하고 이를 초과하는 단어 수 반복 구절은 감지하지 않음                          